### PR TITLE
Please for the love of god

### PR DESCRIPTION
**Pull request by RacoonDog**
i cant take this anymore

### CODE REVIEW

**Review by RedCarlos26 — COMMENTED** [review]
Why would you do that lmao

**Comment by RedCarlos26** [comment]
I could make an option to make the window icon custom tho

**Comment by RacoonDog** [comment]
its just annoying imo

**Comment by RedCarlos26** [comment]
Yea that's kinda true I'll remove it or set it as an option.

**Comment by RedCarlos26** [comment]
I have implemented better what you suggested. Will be available in the next release.

**Pull request closed without merging**
